apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-jq-demo
  labels:
    app: argocd-jq-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-jq-demo
  template:
    metadata:
      labels:
        app: argocd-jq-demo
    spec:
      containers:
        - name: argocd-jq-demo-http
          image: "{{ .Values.image.repository }}:{{ default .Values.image.tag }}"
          ports:
            - containerPort: 80
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jqPathExpressions: 'until(true == false; [.] + [1])'
